Test Org - Speridian/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TIN_EIN__c</fullName>
        <label>TIN/EIN</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ba_Email_Address__c</fullName>
        <label>Email Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_GroupStatus__c</fullName>
        <label>Group Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Partially U/W</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Former Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_RatingCounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rating County</label>
        <referenceTo>BA_Zipcode_Admin__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Address__c.object
<CustomObject>
    <fields>
        <fullName>ba_AddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_AddressLine_1__c</fullName>
        <label>Address Line 1</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_AddressType__c</fullName>
        <label>Address Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Principal</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_State__c</fullName>
        <label>State</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Zipcode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zipcode</label>
        <referenceTo>BA_Zipcode_Admin__c</referenceTo>
        <relationshipLabel>Address</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Task_Chapter__c.object
<CustomObject>
    <description>Task Chapters</description>
    <fields>
        <fullName>ba_Chapter_Component_Name__c</fullName>
        <description>Lightning Component Name</description>
        <label>Chapter Component Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Chapter_Name__c</fullName>
        <description>Chapter Name</description>
        <inlineHelpText>TaskName_ChapterName</inlineHelpText>
        <label>Chapter Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ba_Display_Name__c</fullName>
        <label>Display Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Sequence_Number__c</fullName>
        <description>Chapter Sequence Number in Context of Parent Task</description>
        <label>Task Sequence Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ba_Task_Flow__c</fullName>
        <description>Parent Task Flow</description>
        <label>Task Flow</label>
        <referenceTo>BA_Task_Flow__c</referenceTo>
        <relationshipLabel>Task Chapters</relationshipLabel>
        <relationshipName>Task_Chapters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task Chapter</label>
    <nameField>
        <displayFormat>BA-TCHPTR-{000000}</displayFormat>
        <label>Chapter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Chapters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Task_Flow__c.object
<CustomObject>
    <description>Administration Table which Maintains List of Taskflows</description>
    <fields>
        <fullName>ba_Chapter_Name__c</fullName>
        <label>Chapter Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Display_Name__c</fullName>
        <description>Display Name For The Task</description>
        <label>Display Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Task_Name__c</fullName>
        <description>Unique Name For the Task</description>
        <label>Task Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Task Flow</label>
    <nameField>
        <displayFormat>BA-Task-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Zipcode_Admin__c.object
<CustomObject>
    <fields>
        <fullName>ba_City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_State__c</fullName>
        <label>State</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Zipcode Administration</label>
    <nameField>
        <label>Rating Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zipcode Administrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ba_ExchangeMemberID__c</fullName>
        <label>Exchange Member ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_ParentMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Parent Member)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ba_RatingCounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rating County</label>
        <referenceTo>BA_Zipcode_Admin__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/classes/TaskflowAdminDAOClass.cls
public with sharing class TaskflowAdminDAOClass {
	
	
	@AuraEnabled
	 public static List<BA_Task_Chapter__c> getTaskChapters(String taskName) {
        // Add Check to make sure all fields are accessible to this user
        return [SELECT Id, ba_Sequence_Number__c, Name, ba_Chapter_Name__c, ba_Display_Name__c, ba_Chapter_Component_Name__c
                FROM BA_Task_Chapter__c WHERE ba_Task_Flow__r.ba_Task_Name__c =: taskName ORDER BY ba_Sequence_Number__c];
    }
    
    @AuraEnabled
	 public static Account getGroupInformation(String GroupId) {
        // Add Check to make sure all fields are accessible to this user
        return [SELECT Id, Name, ba_Email_Address__c, ba_RatingCounty__c, TIN_EIN__c, ba_GroupStatus__c from Account where id=:GroupId];
    }
    
    
    
    @AuraEnabled
    public static MemberSearchController.Memberdetails fetchmember(String memberId) {
    	MemberSearchController.Memberdetails member=new MemberSearchController.Memberdetails();
     try{
  // Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
  Contact con=new Contact();
   con=[Select id,name,ba_ParentMember__c,ba_ExchangeMemberID__c,ba_RatingCounty__c,Phone,Birthdate, RecordTypeId, RecordType.Name from Contact
   						 where id=:memberId LIMIT 1
   						        ];
   						        system.debug('RecordTYpe'+con.RecordType.Name);
   	if(con.RecordType.Name=='Member'){
   		
   	
         member.MemberId=con.ba_ExchangeMemberID__c;
 		 member.MemberName=con.name;
         member.Phone=con.Phone;
         member.Birthdate=con.Birthdate;
         
   BA_Address__c addr=new BA_Address__c();
    addr=[Select id,ba_Zipcode__r.ba_Zipcode__c, ba_AddressLine_1__c, ba_AddressLine2__c, ba_City__c, ba_State__c from BA_Address__c 
                                where ba_AddressType__c='Principal'
                                 AND ba_Zipcode__c=:con.ba_RatingCounty__c];
 
 		system.debug('Contact'+addr.ba_Zipcode__r.ba_Zipcode__c);	
 		
 		
 		if(addr!=null){
 		member.Address1=addr.ba_AddressLine_1__c;
 		member.Address2=addr.ba_AddressLine2__c;
 		member.City=addr.ba_City__c;
 		member.State=addr.ba_State__c;
 		member.ZipCode=addr.ba_Zipcode__r.ba_Zipcode__c;
 		}
 		system.debug('Contact'+member);
        return member;
     }
     else if(con.RecordType.Name=='Authorized Contact'){
     	contact auth=[Select id,name,ba_ExchangeMemberID__c,ba_RatingCounty__c,Phone,Birthdate, RecordTypeId, RecordType.Name from Contact
   						 where id=:con.ba_ParentMember__c];
   		system.debug('Authorized Contact'+auth);
   		member.MemberId=auth.ba_ExchangeMemberID__c;
 		 member.MemberName=auth.name;
         member.Phone=auth.Phone;
         member.Birthdate=auth.Birthdate;
         
   
    BA_Address__c addr=[Select id,ba_Zipcode__r.ba_Zipcode__c, ba_AddressLine_1__c, ba_AddressLine2__c, ba_City__c, ba_State__c from BA_Address__c 
                                where ba_AddressType__c='Principal'
                                 AND ba_Zipcode__c=:auth.ba_RatingCounty__c ];
 
 		system.debug('Contact'+addr.ba_Zipcode__r.ba_Zipcode__c);	
 		
 		
 		
 		member.Address1=addr.ba_AddressLine_1__c;
 		member.Address2=addr.ba_AddressLine2__c;
 		member.City=addr.ba_City__c;
 		member.State=addr.ba_State__c;
 		member.ZipCode=addr.ba_Zipcode__r.ba_Zipcode__c;
 		system.debug('Authorized Contact Member'+member);
        return member;
   		
     	

}
     
    
     }
     catch(QueryException e){
         
     }
       return member; 
    }
     
    
     
    
}