Test Org - Speridian/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TIN_EIN__c</fullName>
        <label>TIN/EIN</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ba_EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ba_Email_Address__c</fullName>
        <label>Email Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_GroupStatus__c</fullName>
        <label>Group Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Partially U/W</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Former Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_LegalEntityName__c</fullName>
        <label>Legal Entity Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_RatingCity__c</fullName>
        <label>Rating City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_RatingCounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rating County</label>
        <referenceTo>BA_Zipcode_Admin__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ba_RatingZipcode__c</fullName>
        <label>Rating Zipcode</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/Ba_Account_Addr_Intersection__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>BA_Address__c</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Address__c.object
<CustomObject>
    <fields>
        <fullName>ba_AddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_AddressLine3__c</fullName>
        <label>Address Line 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_AddressLine_1__c</fullName>
        <label>Address Line 1</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_County__c</fullName>
        <label>County</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_State__c</fullName>
        <label>State</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Zipcode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zipcode</label>
        <referenceTo>BA_Zipcode_Admin__c</referenceTo>
        <relationshipLabel>Address</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_SicCode__c.object
<CustomObject>
    <fields>
        <fullName>ba_SICCode__c</fullName>
        <label>SIC Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SIC Code</label>
    <nameField>
        <label>SIC Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIC Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Zipcode_Admin__c.object
<CustomObject>
    <fields>
        <fullName>ba_City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_State__c</fullName>
        <label>State</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Zipcode Administration</label>
    <nameField>
        <label>Rating Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zipcode Administrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/classes/Ba_GroupSummaryClass.cls
public with sharing class Ba_GroupSummaryClass {
    
    
    @AuraEnabled
	public static Account getGroupInformation(String GroupId) {
		// Add Check to make sure all fields are accessible to this user
	return [SELECT Id, Name, AccountNumber,ba_LegalEntityName__c,ba_EffectiveDate__c,Ownership,Sic, ba_Email_Address__c, ba_RatingCounty__c,ba_RatingCounty__r.Name, TIN_EIN__c, ba_GroupStatus__c,ba_RatingZipcode__c,
			 ba_RatingCity__c
			 from Account where id =: GroupId];

	}
	
	   @AuraEnabled
	public static BA_Address__c  getGroupAddress(String GroupId) {
		// Add Check to make sure all fields are accessible to this user
	   Ba_Account_Addr_Intersection__c intersect=[Select id,Address__c 
	   												from Ba_Account_Addr_Intersection__c 
	   												where Account__c=:GroupId
	   												AND Primary__c=true
	   												LIMIT 1];	
	   												
	   BA_Address__c addrlst =[Select id, ba_AddressLine_1__c, ba_AddressLine2__c, ba_AddressLine3__c, ba_City__c, ba_County__c, ba_State__c, ba_Zipcode__c
	   									from BA_Address__c
	   									where id=:intersect.Address__c LIMIT 1];
	   
	   return addrlst;

	}
	
	 @AuraEnabled
	public static list<BA_SicCode__c>  getGroupSIC() {
	list <BA_SicCode__c> SIClist=[Select id, Name, ba_SICCode__c from BA_SicCode__c];
	return SIClist;
	}
	
	 @AuraEnabled
	public static list<BA_Zipcode_Admin__c>  getGroupZip() {
		list<BA_Zipcode_Admin__c> ziplist = [Select id,Name, ba_Zipcode__c, ba_County__c, ba_City__c from BA_Zipcode_Admin__c  ];
		return ziplist;
	}
	
	 @AuraEnabled
	public static void  changedate(String GroupId, String Effdate) {
		Account acc=new Account(id=GroupId);
		acc.ba_EffectiveDate__c=Date.valueof(Effdate);
		update acc;
	}
	
	
	 @AuraEnabled
	public static list<String>  getIndustryInfo() {
		List<String> options = new List<String>();
        
   Schema.DescribeFieldResult fieldResult =
 Account.Industry.getDescribe();
   List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
   for( Schema.PicklistEntry f : ple)
   {
      options.add(f.getLabel());
   }       
   return options;
	}
	
	
	
}