Test Org - Speridian/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_EG_Contact_Intersection__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Employer Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>BA_EG_Contact_Intersections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Authorized Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>BA_EG_Contact_Intersections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Info</label>
    <nameField>
        <displayFormat>AC-{00000}</displayFormat>
        <label>BA_EG_Contact_Intersection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ba_ExchangeMemberID__c</fullName>
        <label>Exchange Member ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_MemberType__c</fullName>
        <label>Member Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscriber</fullName>
                </value>
                <value>
                    <fullName>Dependent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_Relation__c</fullName>
        <label>Relation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Self</fullName>
                </value>
                <value>
                    <fullName>Dependent</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_TobaccoUse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tobacco Use In Last 6 Months</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dependent</fullName>
        <active>true</active>
        <label>Dependent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <recordTypes>
        <fullName>Subscriber</fullName>
        <active>true</active>
        <description>same as contact object</description>
        <label>Subscriber</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/classes/AddQuoteCensusClass.cls
public with sharing class AddQuoteCensusClass {
	
	 @AuraEnabled
 public static list<Contact> fetchquoteinfo(String GroupId) {
Account acc=[Select Id, Active__c from account where id=:GroupId];
 	if(acc.Active__c=='Yes'){
 	list<BA_EG_Contact_Intersection__c> junction=[Select id, Contact__c from BA_EG_Contact_Intersection__c 
 													where Account__c=:GroupId ];
   list<String> conid=new list<String>();											
   for(BA_EG_Contact_Intersection__c inter:junction){
   	  conid.add(inter.Contact__c);
   }
    list<Contact> con=[Select id, ba_ExchangeMemberID__c, LastName, FirstName, Birthdate, ba_TobaccoUse__c
    					from Contact
    					where id IN:conid 
                      AND ba_MemberType__c='Subscriber'];
    					
 	// Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
 	/* List<Contact> con=[Select id, ba_ExchangeMemberID__c, LastName, FirstName, Birthdate, ba_TobaccoUse__c
 						 from Contact
 						 where RecordTypeId=:recordTypeId]; */
 	return con;
 	}
 	else
 	{
 		return null;
 	}
 }
    
    
   @AuraEnabled
 public static list<Contact> fetchdependents(String GroupId) {
 	list<BA_EG_Contact_Intersection__c> junction=[Select id, Contact__c from BA_EG_Contact_Intersection__c 
 													where Account__c=:GroupId ];
   list<String> conid=new list<String>();											
   for(BA_EG_Contact_Intersection__c inter:junction){
   	  conid.add(inter.Contact__c);
   }
    list<Contact> con=[Select id, ba_ExchangeMemberID__c, LastName, FirstName, Birthdate, ba_Relation__c,ba_TobaccoUse__c
    					from Contact
    					where id IN:conid 
                      AND ba_MemberType__c='Dependent'];
    					
 	// Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
 	/* List<Contact> con=[Select id, ba_ExchangeMemberID__c, LastName, FirstName, Birthdate, ba_TobaccoUse__c
 						 from Contact
 						 where RecordTypeId=:recordTypeId]; */
 	return con;
 }
    
}