Test Org - Speridian/src/objects/BA_Assignment_Skillset__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Size__c</fullName>
        <label>Group Size</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Region__c</fullName>
        <label>Service Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BA_Assignment_Skillsets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA_Assignment_Skillset</label>
    <nameField>
        <label>BA_Assignment_Skillset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA_Assignment_Skillsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org/src/classes/SalesRepListclass.cls
public class SalesRepListclass {
      @AuraEnabled
    public static List<User> AcctTm(){
        
        //insert Mmbr;
     // return [SELECT TeamMemberRole,UserId,User.FirstName,User.LastName,User.IsActive From AccountTeamMember];
      //return [Select First_Name__c,Last_Name__c From BA_Member__c];
      return [SELECT Id,FirstName,LastName,IsActive From User];
    }
     @AuraEnabled
    public static List<BA_Assignment_Skillset__c> QueryAccnt(String Idval){
        ID Id1 = String.valueOf(Idval);
        //insert Mmbr;
     // return [SELECT TeamMemberRole,UserId,User.FirstName,User.LastName,User.IsActive From AccountTeamMember];
      //return [Select First_Name__c,Last_Name__c From BA_Member__c];
      return [SELECT Id,Line_of_Business__c,Service_Region__c,Effective_Date__c,Group_Size__c From BA_Assignment_Skillset__c where UserId__c = :Id1];
    }
    @AuraEnabled
    public static String CrtSalsRp(String UsrId, String GrpId){
       AccountTeamMember Mmbr = new AccountTeamMember(TeamMemberRole='SalesRep',UserId=UsrId,AccountId=GrpId);
      insert Mmbr;
     // return [SELECT TeamMemberRole,UserId,User.FirstName,User.LastName,User.IsActive From AccountTeamMember];
      //return [Select First_Name__c,Last_Name__c From BA_Member__c];
     // return [SELECT TeamMemberRole,UserId,User.FirstName,User.LastName,User.IsActive From AccountTeamMember where TeamMemberRole='SalesRep'];
    return GrpId;
    }

}