Test Org - Speridian/src/objects/BA_Address__c.object
<CustomObject>
    <fields>
        <fullName>ba_AddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_AddressLine_1__c</fullName>
        <label>Address Line 1</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_AddressType__c</fullName>
        <label>Address Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Principal</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_State__c</fullName>
        <label>State</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Zipcode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zipcode</label>
        <referenceTo>BA_Zipcode_Admin__c</referenceTo>
        <relationshipLabel>Address</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Zipcode_Admin__c.object
<CustomObject>
    <fields>
        <fullName>ba_City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_State__c</fullName>
        <label>State</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Zipcode Administration</label>
    <nameField>
        <label>Rating Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zipcode Administrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ba_ExchangeMemberID__c</fullName>
        <label>Exchange Member ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_RatingCounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rating County</label>
        <referenceTo>BA_Zipcode_Admin__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/classes/PCPChangeController.cls
public with sharing class PCPChangeController {
	
	@AuraEnabled
 public static Memberdetails fetchmemberdetails(String memberId) {
   Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
   Contact con=[Select id,name,ba_RatingCounty__c from Contact
   						 where ba_ExchangeMemberID__c=:memberId
   						       AND RecordTypeId=:recordTypeId ];
   
   
    BA_Address__c addr=[Select id,ba_Zipcode__r.ba_Zipcode__c, ba_AddressLine_1__c, ba_AddressLine2__c, ba_City__c, ba_State__c from BA_Address__c 
                                where ba_AddressType__c='Principal'
                                 AND ba_Zipcode__c=:con.ba_RatingCounty__c];
 
 		system.debug('Contact'+con);	
 		
 		Memberdetails member=new Memberdetails();
 		member.MemberId=memberId;
 		member.MemberName=con.name;
 		member.Address1=addr.ba_AddressLine_1__c;
 		member.Address2=addr.ba_AddressLine2__c;
 		member.City=addr.ba_City__c;
 		member.State=addr.ba_State__c;
 		member.ZipCode=addr.ba_Zipcode__r.ba_Zipcode__c;
 		system.debug('Contact'+member);
       return member;
 
 }	
 
 @AuraEnabled
 public static Memberdetails fetchpcpdata(String membername) {
 	
   
   Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Producer').getRecordTypeId();
   
    Contact con=[Select id,name,ba_RatingCounty__c,phone from Contact where name=:membername AND RecordTypeId=:recordTypeId];
   
    BA_Address__c addr=[Select id,ba_Zipcode__r.ba_Zipcode__c, ba_AddressLine_1__c, ba_AddressLine2__c, ba_City__c, ba_State__c from BA_Address__c 
                                where ba_AddressType__c='Principal'
                                 AND ba_Zipcode__c=:con.ba_RatingCounty__c];
 
 		system.debug('Contact'+addr.ba_Zipcode__r.ba_Zipcode__c);	
 		
 		Memberdetails pcp=new Memberdetails();
 		
 		pcp.MemberName=membername;
 		pcp.Address1=addr.ba_AddressLine_1__c;
 		pcp.Address2=addr.ba_AddressLine2__c;
 		pcp.Phone=con.Phone;
 		pcp.City=addr.ba_City__c;
 		pcp.State=addr.ba_State__c;
 		pcp.ZipCode=addr.ba_Zipcode__r.ba_Zipcode__c;
 		system.debug('Contact'+pcp);
       return pcp;
 					

 
 
 }	
 
 
 public with sharing class Memberdetails {
 	@AuraEnabled 
    public String MemberId;
    
    @AuraEnabled 
    public String MemberName;
    
      @AuraEnabled 
    public String Phone;
    
    @AuraEnabled 
    public String Address1;
    
    @AuraEnabled 
    public String Address2;
    
    @AuraEnabled 
    public String City;
    
    @AuraEnabled 
    public String State;
    
    @AuraEnabled 
    public String ZipCode;
    
    
    
    public Memberdetails() {
       
  }
 
 	
 	
 } 

}