Test Org - Speridian/src/objects/BA_Asset__c.object
<CustomObject>
    <fields>
        <fullName>ba_BenefitPackage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predefined Packages</label>
        <referenceTo>BA_Product_Flat__c</referenceTo>
        <relationshipLabel>Benefit Package</relationshipLabel>
        <relationshipName>Benefit_Package</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ba_QuoteLineID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote Line</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Benefit Package</relationshipLabel>
        <relationshipName>Benefit_Package</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ba_RateEffectiveDate__c</fullName>
        <label>Rate Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ba_RateTerminationDate__c</fullName>
        <label>Rate Termination Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ba_RatingRegion__c</fullName>
        <label>Rating Region</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Benefit Package</label>
    <nameField>
        <label>Benefit Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Package</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Class_Package__c.object
<CustomObject>
    <fields>
        <fullName>ba_BenefitPackageID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Benefit Package</label>
        <referenceTo>BA_Asset__c</referenceTo>
        <relationshipLabel>Group Class Packages</relationshipLabel>
        <relationshipName>Group_Class_Packages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ba_ClassID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Class ID</label>
        <referenceTo>BA_Classes__c</referenceTo>
        <relationshipLabel>Group Class Packages</relationshipLabel>
        <relationshipName>Group_Class_Packages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ba_RateEffectiveDate__c</fullName>
        <label>Rate Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ba_RateTerminationDate__c</fullName>
        <label>Rate Termination Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Group Class Package</label>
    <nameField>
        <label>Group Class Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Class Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/classes/Ba_SubGroupClasslstClass.cls
public with sharing class Ba_SubGroupClasslstClass {
    
    
    @AuraEnabled
    public static void getbenefitpackage(Id classId){
        list<Id> Idlst=new list<Id>();
       /* list<BA_Class_Package__c> packagelst = [Select ba_BenefitPackageID__c from BA_Class_Package__c 
                                        where ba_ClassID__c=:classId];
                                        
        for(BA_Class_Package__c pack: packagelst){
            Idlst.add(pack.ba_BenefitPackageID__c);
        }
        
        list<BA_Asset__c> benefitlst = [Select id,ba_QuoteLineID__c,ba_RatingRegion__c,Name, ba_BenefitPackage__c, ba_Status__c,    ba_RateEffectiveDate__c, ba_RateTerminationDate__c
                                        from BA_Asset__c where id IN:Idlst ];
        SubGroupWrpClass wrp=new SubGroupWrpClass();
        wrp.benefitpackagelst=benefitlst;
        return wrp;*/
        
    }
    
    
    
    
    
    public with sharing class SubGroupWrpClass {
         
    @AuraEnabled
        public list < BA_Asset__c > benefitpackagelst; 
    }
}