Test Org - Speridian/src/objects/BA_Assignment_Skillset__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Size__c</fullName>
        <label>Group Size</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Region__c</fullName>
        <label>Service Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BA_Assignment_Skillsets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA_Assignment_Skillset</label>
    <nameField>
        <label>BA_Assignment_Skillset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BA_Assignment_Skillsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org/src/classes/QuoteSalesRepListclass.cls
public class QuoteSalesRepListclass {
      @AuraEnabled
    public static List<User> AcctTm(){
      return [SELECT Id,FirstName,LastName,IsActive From User];
    }
     @AuraEnabled
    public static List<BA_Assignment_Skillset__c> QueryAccnt(String Idval){
      //ID Id1 = String.valueOf(Idval);
     // system.debug(Idval);
      return [SELECT Id,Line_of_Business__c,Service_Region__c,Effective_Date__c,Group_Size__c From BA_Assignment_Skillset__c where UserId__c = :Idval];
    }
    @AuraEnabled
    public static List<AccountTeamMember> CrtSalsRp(String UsrId, String GrpId){
          return [SELECT TeamMemberRole,UserId,User.FirstName,User.LastName,User.IsActive,AccountId From AccountTeamMember where AccountId = :GrpId ];
       
    }

}