Test Org - Speridian/src/objects/BA_Classes__c.object
<CustomObject>
    <fields>
        <fullName>Enrollable_Class__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrollable Class</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Selection__c</fullName>
        <defaultValue>false</defaultValue>
        <description>just added for easy implementation of Ba_EnrollableClassSelctionLstCmp component in group installation flow</description>
        <label>Selection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ba_ClassDescription__c</fullName>
        <label>Class Description</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_ProbationaryPeriod__c</fullName>
        <label>Probationary Period</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FOMF 60 Days</fullName>
                </value>
                <value>
                    <fullName>FOMF 90 Days</fullName>
                </value>
                <value>
                    <fullName>FOMF DOH</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Group Classes</label>
    <nameField>
        <label>Class ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/classes/Ba_GroupClassesDAOClass.cls
public with sharing class Ba_GroupClassesDAOClass {   
    @Auraenabled
    public static string getValues(){
    		//Query the object of choice
    		List<BA_Classes__c> ac = [select Name, ba_ClassDescription__c, Enrollable_Class__c FROM BA_Classes__c];
           // List<BA_Classes__c> bc = [SELECT ba_ProbationaryPeriod__c FROM BA_Classes__c];
       
		system.debug(ac);
		String jsonLst = JSON.serialize(ac, true);
		// This part needs the object Name and the list of api name of the fields (case sensitive). This is needed explicitly, because
		// in the query above, if fields do not have a value in them, the result records will not have the field token at all.
		String objNm = 'BA_Classes__c';
        Boolean SId = false;
		List<String> fList = new List<String>();
		//flist.add('Selection__c');
        flist.add('Name');
		fList.add('ba_ClassDescription__c');
		flist.add('Enrollable_Class__c');
       
       // flist.add('ba_ProbationaryPeriod__c');
		//sf2jsonUtil.getHeaders(objNm, fList);
		//sf2jsonUtil.getRows(jsonLst,fList);
		//passing all this to the utility
        //return sf2jsonUtil.getJson(jsonLst,fList,objNm) ;
       List<String> objNmrltd = new List<String>();
        List<String> fListrltd = new List<String>();
        List<String> objNmrltdfrrow = new List<String>();
       List<List<String>> My_Array = new List<List<String>>();
        return sf2jsonUtil.getJson(jsonLst,fList,objNm,SId,fListrltd,objNmrltd,objNmrltdfrrow,My_Array);
         //return [SELECT ba_ProbationaryPeriod__c, FROM BA_Classes__c]; 
    }
}