Test Org - Speridian/src/objects/BA_Classes__c.object
<CustomObject>
    <fields>
        <fullName>ba_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Group Classes</relationshipLabel>
        <relationshipName>Group_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ba_ProbationaryPeriod__c</fullName>
        <label>Probationary Period</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FOMF 60 Days</fullName>
                </value>
                <value>
                    <fullName>FOMF 90 Days</fullName>
                </value>
                <value>
                    <fullName>FOMF DOH</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Group Classes</label>
    <nameField>
        <label>Class ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Correspondence__c.object
<CustomObject>
    <fields>
        <fullName>Document_Status__c</fullName>
        <label>Document Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>using for Ba_GroupAttachmentLstCmp component.</description>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ba_CreatedDate__c</fullName>
        <label>Created Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ba_DocumentType__c</fullName>
        <label>Document Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Installation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Correspondence (Group)</relationshipLabel>
        <relationshipName>Correspondence1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Correspondence</label>
    <nameField>
        <label>Document Link</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Correspondence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/classes/Ba_GroupAttachmentClass.cls
public class Ba_GroupAttachmentClass {
@Auraenabled
    public static string Value(String GrpId){
    		//Query the object of choice
    		List<BA_Correspondence__c> ac = [Select id, Name, Document_Status__c, ba_DocumentType__c,ba_CreatedDate__c,ba_Group__c from BA_Correspondence__c where ba_Group__c =:GrpId ];
           // List<BA_Classes__c> bc = [SELECT ba_ProbationaryPeriod__c FROM BA_Classes__c];
       
		system.debug('Test'+ac);
		String jsonLst = JSON.serialize(ac, true);
		// This part needs the object Name and the list of api name of the fields (case sensitive). This is needed explicitly, because
		// in the query above, if fields do not have a value in them, the result records will not have the field token at all.
		String objNm = 'BA_Correspondence__c';
		List<String> fList = new List<String>();
		flist.add('ba_Check__c');
        flist.add('Name');
	//	fList.add('Document_Status__c');
		//flist.add('ba_DocumentType__c');
      //  flist.add('ba_CreatedDate__c');
		//sf2jsonUtil.getHeaders(objNm, fList);
		//sf2jsonUtil.getRows(jsonLst,fList);
		//passing all this to the utility
		system.debug('Test2'+jsonLst);
        system.debug('Test3'+flist);
        
        return sf2jsonUtil.getJson(jsonLst,fList,objNm) ;
}
}