Test Org - Speridian/src/objects/BA_Classes__c.object
<CustomObject>
    <fields>
        <fullName>Enrollable_Class__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrollable Class</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ba_ClassDescription__c</fullName>
        <label>Class Description</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_ClassStatus__c</fullName>
        <label>Class Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ba_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Group Classes</relationshipLabel>
        <relationshipName>Group_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ba_ProbationaryPeriod__c</fullName>
        <label>Probationary Period</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FOMF 60 Days</fullName>
                </value>
                <value>
                    <fullName>FOMF 90 Days</fullName>
                </value>
                <value>
                    <fullName>FOMF DOH</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Group Classes</label>
    <nameField>
        <label>Class ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org/src/classes/Ba_GroupClassPackageClass.cls
public class Ba_GroupClassPackageClass {
    
    
    @AuraEnabled
    public static list<BA_Classes__c> getClassinfo(String groupId){
        
        list<BA_Classes__c> classlist=[Select Id, ba_ClassDescription__c, Name, ba_EffectiveDate__c	, Enrollable_Class__c, ba_ProbationaryPeriod__c,ba_ClassStatus__c
                                      from BA_Classes__c where ba_Group__c =: groupId  ];
        return classlist;
        
        
    }

}