Test Org - Speridian/src/objects/BA_Eligiblity_Administration__c.object
<CustomObject>
    <fields>
        <fullName>ba_Eligiblity_Question__c</fullName>
        <label>Eligiblity Question</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eligiblity Administration</label>
    <nameField>
        <displayFormat>EA{0000}</displayFormat>
        <label>Eligiblity Administration  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligiblity Administrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org/src/classes/EligibilityInfoClass.cls
public with sharing  class EligibilityInfoClass {
	
	@AuraEnabled
 public static List < EligibilityInfoClass.EligibilityInfoWrpClass > fetchquestions() {
 	list<EligibilityInfoWrpClass> eligiblelist=new list<EligibilityInfoWrpClass>();
 	
 	list<BA_Eligiblity_Administration__c> eligibilitylist=[Select ba_Eligiblity_Question__c from BA_Eligiblity_Administration__c ];
 	for(BA_Eligiblity_Administration__c admin:eligibilitylist ){
 		EligibilityInfoClass.EligibilityInfoWrpClass info=new EligibilityInfoWrpClass();
 		info.question=admin.ba_Eligiblity_Question__c;
 		eligiblelist.add(info);
 	}
 	return eligiblelist;
 	
 }
    
   
 
 /*Wrapper class for eligibility information*/
 
 public with sharing class EligibilityInfoWrpClass {
 	@AuraEnabled 
    public String infodata;
    
    @AuraEnabled 
    public string question;
    
    public EligibilityInfoWrpClass() {
       
  }
 
 	
 	
 } 

}