Test Org - Speridian/src/objects/BA_Group_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ba_CompetitorName__c</fullName>
        <label>Competitor Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_ContractsEnrolled__c</fullName>
        <label>Contracts Enrolled</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ba_Created__c</fullName>
        <label>Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ba_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Group Competitors</relationshipLabel>
        <relationshipName>Group_Competitors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Group Competitor</label>
    <nameField>
        <displayFormat>GC-{0000}</displayFormat>
        <label>Group Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org/src/classes/CompetitorDAOClass.cls
public with sharing class CompetitorDAOClass {

    @AuraEnabled
    public static List<BA_Group_Competitor__c> getGroupCompetitors(String parentGroupId) {
        // Add Check to make sure all fields are accessible to this user
        return [SELECT Id, ba_CompetitorName__c, ba_ContractsEnrolled__c, ba_Created__c, ba_Group__c, 	Notes__c
                FROM BA_Group_Competitor__c WHERE ba_Group__c=: parentGroupId];
    }
    
    @AuraEnabled
    public static BA_Group_Competitor__c saveCompetitor(BA_Group_Competitor__c competitor) {
        // Perform isUpdatable() checking first, then
        
        // Set Custom 'System Fields' 
        competitor.put('ba_Created__c',system.now());
        
        upsert competitor;
        return competitor;
    }
    
     @AuraEnabled
    public static BA_Group_Competitor__c deleteCompetitor(BA_Group_Competitor__c competitor) {
        // Perform isUpdatable() checking first, then
        delete competitor;
        
        return competitor;
    }
}