Test Org - Speridian/src/objects/BA_Group_Competitor_Product__c.object
<CustomObject>
    <fields>
        <fullName>ba_ParentCompetitor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Parent Competitor</label>
        <referenceTo>BA_Group_Competitor__c</referenceTo>
        <relationshipLabel>Group Competitor Products</relationshipLabel>
        <relationshipName>Group_Competitor_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Group Competitor Product</label>
    <nameField>
        <displayFormat>GCP-{0000}</displayFormat>
        <label>Group Competitor Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Competitor Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/classes/CompetitorProductDAOClass.cls
public with sharing class CompetitorProductDAOClass {

    @AuraEnabled
    public static List < BA_Group_Competitor_Product__c > getCompetitorProducts(String parentCompetitorId) {
        // Add Check to make sure all fields are accessible to this user
        return [SELECT Id,  Name,
            ba_ParentCompetitor__c
           
            FROM BA_Group_Competitor_Product__c WHERE ba_ParentCompetitor__c =: parentCompetitorId
        ];
    }
        
         @AuraEnabled
    public static BA_Group_Competitor_Product__c saveCompetitorProduct(BA_Group_Competitor_Product__c competitorproduct) {
        // Perform isUpdatable() checking first, then
        
        // Set Custom 'System Fields' 

        
        upsert competitorproduct;
        return competitorproduct;
    }
    
     @AuraEnabled
    public static BA_Group_Competitor_Product__c deleteCompetitorProduct(BA_Group_Competitor_Product__c competitorproduct) {
        // Perform isUpdatable() checking first, then
        delete competitorproduct;
        
        return competitorproduct;
    }
}