Test Org - Speridian/src/objects/BA_Group_Class_Administration__c.object
<CustomObject>
    <fields>
        <fullName>ba_Class_Description__c</fullName>
        <label>Class Description</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Class_Type__c</fullName>
        <label>Class Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_EnrollableClass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrollable Class</label>
        <type>Checkbox</type>
    </fields>
    <label>Group Class Administration</label>
    <nameField>
        <label>Class Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Class Administration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Product_Flat__c.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Ancilliary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_PackageName__c</fullName>
        <label>Package Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ba_ProductLine__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_ProductType__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HMO</fullName>
                </value>
                <value>
                    <fullName>PPO</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Predefined Packages</label>
    <nameField>
        <label>Predefined Packages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Predefined Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/ba_Quote_Request_Class__c.object
<CustomObject>
    <fields>
        <fullName>ba_ClassDescription__c</fullName>
        <label>Class Description</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ba_EnrollableClass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrollable Class</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ba_ProbationaryPeriod__c</fullName>
        <label>Probationary Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FOMF 60 Days</fullName>
                </value>
                <value>
                    <fullName>FOMF 90 Days</fullName>
                </value>
                <value>
                    <fullName>FOMF DOH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Request Class</label>
    <nameField>
        <label>Quote Request Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Request Class</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org/src/classes/Ba_QuoteClassPackageAssociationDAOClass.cls
public class Ba_QuoteClassPackageAssociationDAOClass {

    
    @Auraenabled
    public static string getClasses(String[] ClsId){
    		//Query the object of choice
    		//List<SObject> Qt = [select ba_ClassDescription__c, Name, ba_EffectiveDate__c,ba_ProbationaryPeriod__c from ba_Quote_Request_Class__c where Id in :ClsId];
	List<SObject> Qt = [select ba_Class_Description__c, Name, ba_Class_Type__c,ba_EnrollableClass__c from BA_Group_Class_Administration__c where Id in :ClsId];
			
        
        system.debug(Qt);
       
		String jsonLst = JSON.serialize(Qt, true);
         system.debug(jsonLst);
		// This part needs the object Name and the list of api name of the fields (case sensitive). This is needed explicitly, because
		// in the query above, if fields do not have a value in them, the result records will not have the field token at all.
		//String objNm = 'ba_Quote_Request_Class__c';
		String objNm = 'BA_Group_Class_Administration__c';
		List<String> fList = new List<String>();
       //s flist.add('Id');
        flist.add('Name');
		//flist.add('ba_ClassDescription__c');
        //flist.add('ba_ProbationaryPeriod__c');
       // flist.add('ba_EffectiveDate__c');
       flist.add('ba_Class_Type__c');
        flist.add('ba_EnrollableClass__c');
        
		
		
        Boolean Isd = true; 
     List<String> objNmrltd = new List<String>();
        List<String> fListrltd = new List<String>();
        List<String> objNmrltdfrrow = new List<String>();
        List<List<String>> My_Array = new List<List<String>>();
		//sf2jsonUtil.getHeaders(objNm, fList);
		//sf2jsonUtil.getRows(jsonLst,fList);
		//passing all this to the utility
		return sf2jsonUtil.getJson(jsonLst,fList,objNm,Isd,fListrltd,objNmrltd,objNmrltdfrrow,My_Array);
    }
       
     @Auraenabled
    public static string getPackages( String[] PkgId){
        
        system.debug('PkgId'+PkgId);
    		//Query the object of choice
    		List<SObject> PP = [Select Ba_PackageName__c,Name,ba_ProductLine__c,Product_Category__c,ba_ProductType__c From Ba_Product_Flat__c where Id in :PkgId];
		system.debug(PP);
       
		String jsonLst = JSON.serialize(PP, true);
         system.debug(jsonLst);
		// This part needs the object Name and the list of api name of the fields (case sensitive). This is needed explicitly, because
		// in the query above, if fields do not have a value in them, the result records will not have the field token at all.
		String objNm = 'Ba_Product_Flat__c';
		List<String> fList = new List<String>();
       //s flist.add('Id');
        flist.add('Name');
		flist.add('Ba_PackageName__c');
        flist.add('ba_ProductLine__c');
        flist.add('Product_Category__c');
        flist.add('ba_ProductType__c');
        
		
		
        Boolean Isd = false; 
     List<String> objNmrltd = new List<String>();
        List<String> fListrltd = new List<String>();
        List<String> objNmrltdfrrow = new List<String>();
        List<List<String>> My_Array = new List<List<String>>();
		//sf2jsonUtil.getHeaders(objNm, fList);
		//sf2jsonUtil.getRows(jsonLst,fList);
		//passing all this to the utility
		return sf2jsonUtil.getJson(jsonLst,fList,objNm,Isd,fListrltd,objNmrltd,objNmrltdfrrow,My_Array);
    }

}