Test Org - Speridian/src/objects/BA_Product_Flat__c.object
<CustomObject>
    <fields>
        <fullName>ba_ProductLine__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Predefined Packages</label>
    <nameField>
        <label>Predefined Packages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Predefined Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Quote_Line_Census__c.object
<CustomObject>
    <fields>
        <fullName>Quote_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Quote Line Census</relationshipLabel>
        <relationshipName>Quote_Line_Census</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>16</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ba_Age__c</fullName>
        <formula>((TODAY()-ba_MemberDOB__c )/365.25)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ba_EmployeeNumber__c</fullName>
        <label>Employee Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_FamilyRate__c</fullName>
        <label>Family Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ba_MemberDOB__c</fullName>
        <label>Date Of Birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ba_Relation__c</fullName>
        <label>Relation</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Self</fullName>
                </value>
                <value>
                    <fullName>Dependent</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_Tobbacco_Usage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tobbacco Usage</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote Line Census</label>
    <nameField>
        <displayFormat>QLC-ID{0000}</displayFormat>
        <label>Quote Line Census Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Census</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>ba_RatingRegion__c</fullName>
        <label>Rating Region</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Predefined_Packages__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predefined Packages</label>
        <referenceTo>BA_Product_Flat__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ba_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/classes/Ba_QuoteLineItemReviewDataGridClass.cls
public class Ba_QuoteLineItemReviewDataGridClass {
 @Auraenabled
    public static string getQLI(String[] QLIId){
    		//Query the object of choice
    		List<QuoteLineItem> Qt = [select Id,Product2.Name, ServiceDate,Predefined_Packages__r.ba_ProductLine__c,LineNumber,QuoteId,Quote.Ba_RatingRegion__c,ba_Status__c From QuoteLineItem where Id in :QLIId];
		system.debug(Qt);
		String jsonLst = JSON.serialize(Qt, true);
		// This part needs the object Name and the list of api name of the fields (case sensitive). This is needed explicitly, because
		// in the query above, if fields do not have a value in them, the result records will not have the field token at all.
		String objNm = 'QuoteLineItem';
		List<String> fList = new List<String>();
        flist.add('Id');
        flist.add('QuoteId');
        flist.add('ba_Status__c');
        flist.add('LineNumber');
       // flist.add('Predefined_Packages__r.ba_ProductLine__c');
		//fList.add('Product2.Name');
		flist.add('ServiceDate');
        
        
        
           
		//sf2jsonUtil.getHeaders(objNm, fList);
		//sf2jsonUtil.getRows(jsonLst,fList);
		//passing all this to the utility
		return sf2jsonUtil.getJson(jsonLst,fList,objNm);
    }
    
    
      @Auraenabled
    public static string getQCensus(String QLIId){
    		//Query the object of choice
    		List<Ba_Quote_Line_Census__c> Qt = [select id,ba_Age__c,ba_MemberDOB__c,ba_Relation__c,ba_FamilyRate__c,Rate__c, ba_Tobbacco_Usage__c, ba_EmployeeNumber__c from Ba_Quote_Line_Census__c where Quote_Line__c= :QLIId];
		system.debug(Qt);
		String jsonLst = JSON.serialize(Qt, true);
		// This part needs the object Name and the list of api name of the fields (case sensitive). This is needed explicitly, because
		// in the query above, if fields do not have a value in them, the result records will not have the field token at all.
		String objNm = 'Ba_Quote_Line_Census__c';
		List<String> fList = new List<String>();
        flist.add('ba_EmployeeNumber__c');
        flist.add('ba_Relation__c');
        flist.add('ba_MemberDOB__c');
        flist.add('ba_Age__c');
		flist.add('ba_FamilyRate__c');
		fList.add('ba_Tobbacco_Usage__c');
        fList.add('Rate__c');
	
     
     
		//sf2jsonUtil.getHeaders(objNm, fList);
		//sf2jsonUtil.getRows(jsonLst,fList);
		//passing all this to the utility
		return sf2jsonUtil.getJson(jsonLst,fList,objNm);
    }
}