Test Org - Speridian/src/objects/BA_Quote_Line_Census__c.object
<CustomObject>
    <fields>
        <fullName>Quote_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Quote Line Census</relationshipLabel>
        <relationshipName>Quote_Line_Census</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ba_FamilyRate__c</fullName>
        <label>Family Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line Census</label>
    <nameField>
        <displayFormat>QLC-ID{0000}</displayFormat>
        <label>Quote Line Census Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Census</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ba_FinancialArrangement__c</fullName>
        <label>Financial Arrangement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Community Rated</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Retrospective</fullName>
                </value>
                <value>
                    <fullName>Minimum Premium</fullName>
                </value>
                <value>
                    <fullName>Premium Credit</fullName>
                </value>
                <value>
                    <fullName>Contingent Premium</fullName>
                </value>
                <value>
                    <fullName>ASC/ASO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>ba_RatingMethodology__c</fullName>
        <label>Rating Methodology</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Average Enrolled Amount</fullName>
                </value>
                <value>
                    <fullName>Composite</fullName>
                </value>
                <value>
                    <fullName>Member Level Rating</fullName>
                </value>
                <value>
                    <fullName>Age-Banded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_TerminationDate__c</fullName>
        <label>Termination Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>ba_MonthlyRate__c</fullName>
        <label>Monthly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ba_RatingMethodology__c</fullName>
        <label>Rating Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Average Enrollee Amount</fullName>
                </value>
                <value>
                    <fullName>Composite</fullName>
                </value>
                <value>
                    <fullName>Member Level Rating</fullName>
                </value>
                <value>
                    <fullName>Age-Banded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_TerminationDate__c</fullName>
        <label>Termination Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/classes/Ba_QuoteLineItemReviewClass.cls
public class Ba_QuoteLineItemReviewClass {
   @AuraEnabled   
   public static QuoteLineItem SrchQuote(String QLIId){
      return [Select Id,ba_RatingMethodology__c,ba_TerminationDate__C,ServiceDate,ba_MonthlyRate__C From QuoteLineItem where Id= :QLIId];
             
    }
    @AuraEnabled   
    public static String SrchFA(String QLIId){
        QuoteLineItem QL = new QuoteLineItem();
     QL = [Select QuoteId From QuoteLineItem where Id= :QLIId];
        
        String Qls = String.valueOf(QL.QuoteId);
        System.debug('123'+Qls);
        Quote Op = new Quote();
         
       Op = [Select Opportunity.ba_FinancialArrangement__c From Quote where Id= :Qls];
         
        String Ops = String.valueOf(Op.Opportunity.ba_FinancialArrangement__c);
        System.debug(Ops);
           return Ops;
             
    }
    @AuraEnabled   
    public static QuoteOutputs SrchFR(String QLIId){
        List<ba_Quote_Line_Census__c> QLC = new List<ba_Quote_Line_Census__c>();
     QLC = [Select ba_FamilyRate__c From ba_Quote_Line_Census__c where Quote_Line__c = :QLIId];
  
       QuoteOutputs obj =  new QuoteOutputs();
     
       obj.EntroleeCount =[SELECT count() FROM ba_Quote_Line_Census__c where Quote_Line__c = :QLIId];
           obj.Rate = 0;
        for(integer i=0;i<obj.EntroleeCount;i++)
        {
            obj.Rate = obj.Rate + Integer.valueOf(QLC[i].ba_FamilyRate__c);
        }
        System.debug(obj.Rate);
          return obj;
             
    }
    
   public class QuoteOutputs {
    @AuraEnabled public Integer EntroleeCount {get;set;}
    @AuraEnabled public Integer Rate {get;set;}
  // @AuraEnabled public List<Integer> IdNum {get;set;}
   
}
}