Test Org - Speridian/src/objects/BA_Task_Chapter__c.object
<CustomObject>
    <description>Task Chapters</description>
    <fields>
        <fullName>ba_Chapter_Component_Name__c</fullName>
        <description>Lightning Component Name</description>
        <label>Chapter Component Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Chapter_Name__c</fullName>
        <description>Chapter Name</description>
        <inlineHelpText>TaskName_ChapterName</inlineHelpText>
        <label>Chapter Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ba_Display_Name__c</fullName>
        <label>Display Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Sequence_Number__c</fullName>
        <description>Chapter Sequence Number in Context of Parent Task</description>
        <label>Task Sequence Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ba_Task_Flow__c</fullName>
        <description>Parent Task Flow</description>
        <label>Task Flow</label>
        <referenceTo>BA_Task_Flow__c</referenceTo>
        <relationshipLabel>Task Chapters</relationshipLabel>
        <relationshipName>Task_Chapters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task Chapter</label>
    <nameField>
        <displayFormat>BA-TCHPTR-{000000}</displayFormat>
        <label>Chapter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Chapters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Task_Flow__c.object
<CustomObject>
    <description>Administration Table which Maintains List of Taskflows</description>
    <fields>
        <fullName>ba_Chapter_Name__c</fullName>
        <label>Chapter Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Display_Name__c</fullName>
        <description>Display Name For The Task</description>
        <label>Display Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Task_Name__c</fullName>
        <description>Unique Name For the Task</description>
        <label>Task Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Task Flow</label>
    <nameField>
        <displayFormat>BA-Task-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org/src/classes/TaskflowAdminDAO.cls
public with sharing class TaskflowAdminDAO {
	
	@AuraEnabled
	 public static List<BA_Task_Chapter__c> getTaskChapters(String taskName) {
        // Add Check to make sure all fields are accessible to this user
        return [SELECT Id, ba_Sequence_Number__c, Name, ba_Chapter_Name__c, ba_Display_Name__c, ba_Chapter_Component_Name__c
                FROM BA_Task_Chapter__c WHERE ba_Task_Flow__c =: [SELECT Id FROM BA_Task_Flow__c WHERE ba_Task_Name__c =: taskName]];
    }
    
}