Test Org - Speridian/src/objects/BA_Task_Chapter__c.object
<CustomObject>
    <description>Task Chapters</description>
    <fields>
        <fullName>ba_Chapter_Component_Name__c</fullName>
        <description>Lightning Component Name</description>
        <label>Chapter Component Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Chapter_Name__c</fullName>
        <description>Chapter Name</description>
        <inlineHelpText>TaskName_ChapterName</inlineHelpText>
        <label>Chapter Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ba_Display_Name__c</fullName>
        <label>Display Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Sequence_Number__c</fullName>
        <description>Chapter Sequence Number in Context of Parent Task</description>
        <label>Task Sequence Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ba_Task_Flow__c</fullName>
        <description>Parent Task Flow</description>
        <label>Task Flow</label>
        <referenceTo>BA_Task_Flow__c</referenceTo>
        <relationshipLabel>Task Chapters</relationshipLabel>
        <relationshipName>Task_Chapters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task Chapter</label>
    <nameField>
        <displayFormat>BA-TCHPTR-{000000}</displayFormat>
        <label>Chapter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Chapters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Task_Flow__c.object
<CustomObject>
    <description>Administration Table which Maintains List of Taskflows</description>
    <fields>
        <fullName>ba_Chapter_Name__c</fullName>
        <label>Chapter Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Display_Name__c</fullName>
        <description>Display Name For The Task</description>
        <label>Display Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Task_Name__c</fullName>
        <description>Unique Name For the Task</description>
        <label>Task Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Task Flow</label>
    <nameField>
        <displayFormat>BA-Task-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/Pause_Task__c.object
<CustomObject>
    <fields>
        <fullName>Chapter_Component__c</fullName>
        <label>Chapter Component</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_number__c</fullName>
        <label>Sequence number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stored_Value__c</fullName>
        <label>Stored Value</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Pause Task</label>
    <nameField>
        <label>Pause Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pause Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org/src/classes/TaskFlowClass.cls
public class TaskFlowClass {

    
    @AuraEnabled
     public static List<BA_Task_Chapter__c> getTaskChapters(String taskName, String taskflow) {
        // Add Check to make sure all fields are accessible to this user
             
        
        return [SELECT Id, ba_Sequence_Number__c, Name, ba_Chapter_Name__c, ba_Display_Name__c, ba_Chapter_Component_Name__c
                FROM BA_Task_Chapter__c WHERE ba_Task_Flow__r.ba_Task_Name__c =: taskName ORDER BY ba_Sequence_Number__c];
         
    }
    
    @AuraEnabled
     public static Pause_Task__c getTaskSequence(String taskName, String taskflow) {
        // Add Check to make sure all fields are accessible to this user
             
         list<BA_Task_Chapter__c> chapterlist= [SELECT Id, ba_Sequence_Number__c, Name, ba_Chapter_Name__c, ba_Display_Name__c, ba_Chapter_Component_Name__c
                                                FROM BA_Task_Chapter__c 
                                                WHERE ba_Task_Flow__r.ba_Task_Name__c =: taskName ORDER BY ba_Sequence_Number__c
                                               ];
         list<BA_Task_Chapter__c> tasklist=new list<BA_Task_Chapter__c>();
         if(taskflow!=''){
          Pause_Task__c pause= [Select Chapter_Component__c,Sequence_number__c,Stored_Value__c from Pause_Task__c
                              where id=:taskflow];
    /* BA_Task_Chapter__c chapter=[Select Id, ba_Sequence_Number__c, Name from
                                   BA_Task_Chapter__c where
                                   ba_Chapter_Component_Name__c=:pause.Chapter_Component__c]; */
            return pause;
             
         }
         else{
       return null;
         }
    }
    
    
     @AuraEnabled
     public static void saveFlowdetails(String taskflow, String chapter,Decimal sequence,String objval ) {
      /*   system.debug([Select id,ba_Task_Name__c from BA_
      ]);
         system.debug('Flow'+taskflow);
      Pause_Task__c pause=new Pause_Task__c();
      String component = (String) System.JSON.deserialize(chapter, String.class);
     
      system.debug('Component Name'+component);
      String flowname = (String) System.JSON.deserialize(taskflow, String.class);
       BA_Task_Flow__c flow=  [Select id, ba_Task_Name__c from BA_Task_Flow__c where ba_Task_Name__c=:flowname];
         pause.Task_Flow__c=flow.id;
         pause.Chapter_Component__c=component;
         pause.Stored_Value__c= objval;
         pause.Sequence_number__c=sequence;
         insert pause; */
    }
    
}