Test Org - Speridian/src/objects/BA_Task_Chapter__c.object
<CustomObject>
    <description>Task Chapters</description>
    <fields>
        <fullName>ba_Chapter_Name__c</fullName>
        <description>Chapter Name</description>
        <inlineHelpText>TaskName_ChapterName</inlineHelpText>
        <label>Chapter Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ba_Display_Name__c</fullName>
        <label>Display Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Sequence_Number__c</fullName>
        <description>Chapter Sequence Number in Context of Parent Task</description>
        <label>Task Sequence Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ba_Task_Flow__c</fullName>
        <description>Parent Task Flow</description>
        <label>Task Flow</label>
        <referenceTo>BA_Task_Flow__c</referenceTo>
        <relationshipLabel>Task Chapters</relationshipLabel>
        <relationshipName>Task_Chapters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task Chapter</label>
    <nameField>
        <displayFormat>BA-TCHPTR-{000000}</displayFormat>
        <label>Chapter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Chapters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/BA_Task_Flow__c.object
<CustomObject>
    <description>Administration Table which Maintains List of Taskflows</description>
    <fields>
        <fullName>Ba_Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Chapter_Name__c</fullName>
        <label>Chapter Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Display_Name__c</fullName>
        <description>Display Name For The Task</description>
        <label>Display Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_Task_Name__c</fullName>
        <description>Unique Name For the Task</description>
        <label>Task Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Task Flow</label>
    <nameField>
        <displayFormat>BA-Task-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/Pause_Task__c.object
<CustomObject>
    <fields>
        <fullName>Ba_Parent_Id__c</fullName>
        <label>Parent Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Chapter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task Chapter</label>
        <referenceTo>BA_Task_Chapter__c</referenceTo>
        <relationshipLabel>Pause Tasks</relationshipLabel>
        <relationshipName>Pause_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pause Task</label>
    <nameField>
        <label>Pause Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pause Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Test Org/src/classes/TaskViewClass.cls
public class TaskViewClass {
@AuraEnabled
     public static List<BA_Task_Flow__c> getTaskFlows(String Entity) {
        // Add Check to make sure all fields are accessible to this user
       
      return [SELECT Id,ba_Display_Name__c,CreatedDate,ba_Task_Name__c FROM BA_Task_Flow__c  where ba_Entity_Name__c =:Entity ORDER BY ba_Display_Name__c ];
      
    }
    
    @AuraEnabled
     public static List<Pause_Task__c> getRSMFlows(String Entity) {
         
        String usr = UserInfo.getUserId();
        // Add Check to make sure all fields are accessible to this user
        return [SELECT Name,CreatedById,Task_Chapter__r.ba_Task_Flow__r.ba_Chapter_Name__c,Task_Chapter__r.ba_Sequence_Number__c,Task_Chapter__r.ba_Task_Flow__r.ba_Task_Name__c,Ba_Parent_Id__c FROM Pause_Task__c where createdby.Id=:usr ORDER BY Name ];
    }
}