Test Org - Speridian/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ba_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Test Org - Speridian/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ba_ExchangeMemberID__c</fullName>
        <label>Exchange Member ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org/src/classes/CreateServiceRequestController.cls
public class CreateServiceRequestController {
    
    @AuraEnabled
   public static Case createservice (String memberId,Boolean waitinginfo) {
  Case service=new Case();
  Contact con=[Select id from Contact where ba_ExchangeMemberID__c=:memberId];
  service.Type='PCP Change';
  service.ba_Member__c=con.id;
  service.status='Open';
  insert service;
  Case servicereq=[Select id,CaseNumber,CreatedDate from case where id=:service.id];
  Task t=new Task();			 
   		t.WhatId = servicereq.id;
   		t.status='completed';
   		t.Subject='PCP Change';
   		t.Description='Service Request Created for PCP Change';
   		t.ActivityDate=system.today();
   		t.OwnerId=UserInfo.getUserId();
   		if(waitinginfo){
   		t.status='Pending';
   		}
   		else
   		{
   			t.status='Completed';
   		}
   		insert t;
  return servicereq;
  
 	 	
 }
    

}