Test Org - Speridian/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ba_Relation1__c</fullName>
        <label>Relation</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Group Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ba_TobaccoUse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tobacco Use In Last 6 Months</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dependent</fullName>
        <active>true</active>
        <label>Dependent</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org/src/classes/DependentDetailsClass.cls
public  with sharing class  DependentDetailsClass {
    
    
     @AuraEnabled
 public static list<Contact> fetchDependentDetails() {
     
 	 id recordType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Dependent').getRecordTypeId();
     
 	List<Contact> details=[Select LastName, FirstName,ba_Relation1__c, Birthdate ,ba_TobaccoUse__c from Contact
 						 where RecordTypeId=:recordType];
     
    
 	return details;
 }
    

}