Test Org - Speridian/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ba_ExchangeMemberID__c</fullName>
        <label>Exchange Member ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ba_RatingCounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rating County</label>
        <referenceTo>BA_Zipcode_Admin__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Test Org - Speridian/src/classes/MemberDAOClass.cls
public class MemberDAOClass {
	
	@AuraEnabled
 public static void createtask(String memberId) {
    
     
   Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
   Contact con=[Select id,name,ba_RatingCounty__c,Phone,Birthdate from Contact
   						 where ba_ExchangeMemberID__c=:memberId];
   			Task t=new Task();			 
   		t.WhoId = con.id;
   		t.status='completed';
   		t.Subject='Member Verification';
   		t.Description='Member is Verified and Task is created';
   		t.ActivityDate=system.today();
   		t.OwnerId=UserInfo.getUserId();
   		insert t;
   						 
 }
    
 }